routes/web.php
<?php

Route::get('/', 'HomeController@index')->name('index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::resource('customer', 'CustomersController');
	Route::resource('vet', 'VetsController');
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
});

app/Customers.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Customers extends Model
{
    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/CustomersController.php
<?php

namespace App\Http\Controllers;

use App\Customers;
use App\Http\Requests\CustomerRequest;
use App\Role;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class CustomersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Customers $model)
    {
        return view('customers.index', ['customers' => $model->paginate(15)]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('customers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CustomerRequest $request)
    {
        $user = new User();
        $user->name = $request->name;
        $user->email = $request->email;
        $user->password = Hash::make($request->password);
        $user->role_id = Role::CLIENTE;
        $user->save();

        $customer = new Customers();
        $customer->identity_number = $request->identity_number;
        $customer->cpf = $request->cpf;
        $customer->user_id = $user->id;
        $customer->pataz = $request->pataz;
        $customer->save();

        return redirect()->route('customer.index')->withStatus(__('Cliente criado com sucesso.'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Customers  $customers
     * @return \Illuminate\Http\Response
     */
    public function show(Customers $customers)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Customers  $customer
     * @return \Illuminate\Http\Response
     */
    public function edit(Customers $customer)
    {
        return view('customers.edit', compact('customer'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Customers  $customers
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Customers $customer)
    {
        $customer->user->name = $request->name;
        $customer->user->email = $request->email;
        $customer->user->save();
        $customer->identity_number = $request->identity_number;
        $customer->cpf = $request->cpf;
        $customer->pataz = $request->pataz;
        $customer->save();

        return redirect()->route('customer.index')->withStatus(__('Cliente atualizado com sucesso.'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Customers  $customer
     * @return \Illuminate\Http\Response
     */
    public function destroy(Customers $customer)
    {
        $user = $customer->user;
        $customer->delete();
        $user->delete();

        return redirect()->route('customer.index')->withStatus(__('Cliente removido com sucesso.'));
    }
}

resources/views/customers/create.blade.php
@extends('layouts.app', ['activePage' => 'customers', 'titlePage' => __('Criação de cliente')])

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <form method="post" action="{{ route('customer.store') }}" autocomplete="off" class="form-horizontal">
                        @csrf
                        @method('post')

                        <div class="card ">
                            <div class="card-header card-header-primary">
                                <h4 class="card-title">{{ __('Novo cliente') }}</h4>
                                <p class="card-category"></p>
                            </div>
                            <div class="card-body ">
                                <div class="row">
                                    <div class="col-md-12 text-right">
                                        <a href="{{ route('customer.index') }}"
                                           class="btn btn-sm btn-primary">{{ __('Voltar para lista') }}</a>
                                    </div>
                                </div>

                                <div class="row">
                                    <label class="col-sm-2 col-form-label">{{ __('Nome') }}</label>
                                    <div class="col-sm-7">
                                        <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                            <input class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}"
                                                   name="name" id="input-name" type="text"
                                                   placeholder="{{ __('Nome') }}" value="{{ old('name') }}"
                                                   required="true" aria-required="true"/>
                                            @if ($errors->has('name'))
                                                <span id="name-error" class="error text-danger"
                                                      for="input-name">{{ $errors->first('name') }}</span>
                                            @endif
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <label class="col-sm-2 col-form-label">{{ __('Email') }}</label>
                                    <div class="col-sm-7">
                                        <div class="form-group{{ $errors->has('email') ? ' has-danger' : '' }}">
                                            <input class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}"
                                                   name="email" id="input-email" type="email"
                                                   placeholder="{{ __('Email') }}" value="{{ old('email') }}" required/>
                                            @if ($errors->has('email'))
                                                <span id="email-error" class="error text-danger"
                                                      for="input-email">{{ $errors->first('email') }}</span>
                                            @endif
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <label class="col-sm-2 col-form-label">{{ __('CPF') }}</label>
                                    <div class="col-sm-7">
                                        <div class="form-group{{ $errors->has('cpf') ? ' has-danger' : '' }}">
                                            <input class="form-control{{ $errors->has('cpf') ? ' is-invalid' : '' }}"
                                                   name="cpf" id="input-cpf" type="text" min="11" max="11"
                                                   placeholder="{{ __('CPF') }}" value="{{ old('cpf') }}" required/>
                                            @if ($errors->has('cpf'))
                                                <span id="cpf-error" class="error text-danger"
                                                      for="input-cpf">{{ $errors->first('cpf') }}</span>
                                            @endif
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <label class="col-sm-2 col-form-label">{{ __('Número de identidade') }}</label>
                                    <div class="col-sm-7">
                                        <div class="form-group{{ $errors->has('identity_number') ? ' has-danger' : '' }}">
                                            <input class="form-control{{ $errors->has('identity_number') ? ' is-invalid' : '' }}"
                                                   name="identity_number" id="input-identity_number" type="text"
                                                   placeholder="{{ __('Número de identidade') }}" value="{{ old('identity_number') }}" required/>
                                            @if ($errors->has('identity_number'))
                                                <span id="identity_number-error" class="error text-danger"
                                                      for="input-identity_number">{{ $errors->first('identity_number') }}</span>
                                            @endif
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <label class="col-sm-2 col-form-label">{{ __('Pataz') }}</label>
                                    <div class="col-sm-7">
                                        <div class="form-group{{ $errors->has('pataz') ? ' has-danger' : '' }}">
                                            <input class="form-control{{ $errors->has('pataz') ? ' is-invalid' : '' }}"
                                                   name="pataz" id="input-pataz" type="text"
                                                   placeholder="{{ __('Pataz') }}" value="{{ old('pataz') }}" required/>
                                            @if ($errors->has('pataz'))
                                                <span id="pataz-error" class="error text-danger"
                                                      for="input-pataz">{{ $errors->first('pataz') }}</span>
                                            @endif
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <label class="col-sm-2 col-form-label"
                                           for="input-password">{{ __(' Senha') }}</label>
                                    <div class="col-sm-7">
                                        <div class="form-group{{ $errors->has('password') ? ' has-danger' : '' }}">
                                            <input
                                                class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}"
                                                input type="password" name="password" id="input-password"
                                                placeholder="{{ __('Senha') }}" value="" required/>
                                            @if ($errors->has('password'))
                                                <span id="name-error" class="error text-danger"
                                                      for="input-name">{{ $errors->first('password') }}</span>
                                            @endif
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <label class="col-sm-2 col-form-label"
                                           for="input-password-confirmation">{{ __('Confirmação de senha') }}</label>
                                    <div class="col-sm-7">
                                        <div class="form-group">
                                            <input class="form-control" name="password_confirmation"
                                                   id="input-password-confirmation" type="password"
                                                   placeholder="{{ __('Confirmação de senha') }}" value="" required/>
                                        </div>
                                    </div>
                                </div>

                            </div>
                            <div class="card-footer ml-auto mr-auto">
                                <button type="submit" class="btn btn-primary">{{ __('Criar usuário') }}</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/customers/edit.blade.php
@extends('layouts.app', ['activePage' => 'customers', 'titlePage' => __('Edição de cliente')])

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <form method="post" action="{{ route('customer.update', $customer) }}" autocomplete="off" class="form-horizontal">
                        @csrf
                        @method('put')

                        <div class="card ">
                            <div class="card-header card-header-primary">
                                <h4 class="card-title">{{ __('Editar cliente') }}</h4>
                                <p class="card-category"></p>
                            </div>
                            <div class="card-body ">
                                <div class="row">
                                    <div class="col-md-12 text-right">
                                        <a href="{{ route('customer.index') }}"
                                           class="btn btn-sm btn-primary">{{ __('Voltar para lista') }}</a>
                                    </div>
                                </div>

                                <div class="row">
                                    <label class="col-sm-2 col-form-label">{{ __('Nome') }}</label>
                                    <div class="col-sm-7">
                                        <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                            <input class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}"
                                                   name="name" id="input-name" type="text"
                                                   placeholder="{{ __('Nome') }}" value="{{ old('name', $customer->user->name) }}"
                                                   required="true" aria-required="true"/>
                                            @if ($errors->has('name'))
                                                <span id="name-error" class="error text-danger"
                                                      for="input-name">{{ $errors->first('name') }}</span>
                                            @endif
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <label class="col-sm-2 col-form-label">{{ __('Email') }}</label>
                                    <div class="col-sm-7">
                                        <div class="form-group{{ $errors->has('email') ? ' has-danger' : '' }}">
                                            <input class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}"
                                                   name="email" id="input-email" type="email"
                                                   placeholder="{{ __('Email') }}" value="{{ old('email', $customer->user->email) }}" required/>
                                            @if ($errors->has('email'))
                                                <span id="email-error" class="error text-danger"
                                                      for="input-email">{{ $errors->first('email') }}</span>
                                            @endif
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <label class="col-sm-2 col-form-label">{{ __('CPF') }}</label>
                                    <div class="col-sm-7">
                                        <div class="form-group{{ $errors->has('cpf') ? ' has-danger' : '' }}">
                                            <input class="form-control{{ $errors->has('cpf') ? ' is-invalid' : '' }}"
                                                   name="cpf" id="input-cpf" type="text" min="11" max="11"
                                                   placeholder="{{ __('CPF') }}" value="{{ old('cpf', $customer->cpf) }}" required/>
                                            @if ($errors->has('cpf'))
                                                <span id="cpf-error" class="error text-danger"
                                                      for="input-cpf">{{ $errors->first('cpf') }}</span>
                                            @endif
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <label class="col-sm-2 col-form-label">{{ __('Número de identidade') }}</label>
                                    <div class="col-sm-7">
                                        <div class="form-group{{ $errors->has('identity_number') ? ' has-danger' : '' }}">
                                            <input class="form-control{{ $errors->has('identity_number') ? ' is-invalid' : '' }}"
                                                   name="identity_number" id="input-identity_number" type="text"
                                                   placeholder="{{ __('Número de identidade') }}" value="{{ old('identity_number', $customer->identity_number) }}" required/>
                                            @if ($errors->has('identity_number'))
                                                <span id="identity_number-error" class="error text-danger"
                                                      for="input-identity_number">{{ $errors->first('identity_number') }}</span>
                                            @endif
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <label class="col-sm-2 col-form-label">{{ __('Pataz') }}</label>
                                    <div class="col-sm-7">
                                        <div class="form-group{{ $errors->has('pataz') ? ' has-danger' : '' }}">
                                            <input class="form-control{{ $errors->has('pataz') ? ' is-invalid' : '' }}"
                                                   name="pataz" id="input-pataz" type="text"
                                                   placeholder="{{ __('Pataz') }}" value="{{ old('pataz', $customer->pataz) }}" required/>
                                            @if ($errors->has('pataz'))
                                                <span id="pataz-error" class="error text-danger"
                                                      for="input-pataz">{{ $errors->first('pataz') }}</span>
                                            @endif
                                        </div>
                                    </div>
                                </div>

                            </div>
                            <div class="card-footer ml-auto mr-auto">
                                <button type="submit" class="btn btn-primary">{{ __('Salvar') }}</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/customers/index.blade.php
@extends('layouts.app', ['activePage' => 'customers', 'titlePage' => __('Clientes')])

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-primary">
                            <h4 class="card-title ">{{ __('Clientes') }}</h4>
                            <p class="card-category"> {{ __('Listagem de clientes') }}</p>
                        </div>
                        <div class="card-body">
                            @if (session('status'))
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class="alert alert-success">
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                <i class="material-icons">close</i>
                                            </button>
                                            <span>{{ session('status') }}</span>
                                        </div>
                                    </div>
                                </div>
                            @endif
                            <div class="row">
                                <div class="col-12 text-right">
                                    <a href="{{ route('customer.create') }}"
                                       class="btn btn-sm btn-primary">{{ __('Novo cliente') }}</a>
                                </div>
                            </div>
                            <div class="table-responsive">
                                <table class="table">
                                    <thead class=" text-primary">
                                    <th>
                                        {{ __('Nome') }}
                                    </th>
                                    <th>
                                        {{ __('Email') }}
                                    </th>
                                    <th>
                                        {{ __('Data de criação') }}
                                    </th>
                                    <th>
                                        {{ __('Pataz') }}
                                    </th>
                                    <th class="text-right">
                                        {{ __('Ações') }}
                                    </th>
                                    </thead>
                                    <tbody>
                                    @foreach($customers as $customer)
                                        <tr>
                                            <td>
                                                <a href="{{ route('customer.show', $customer) }}">{{ $customer->user->name }}</a>
                                            </td>
                                            <td>
                                                {{ $customer->user->email }}
                                            </td>
                                            <td>
                                                {{ $customer->user->created_at->format('Y-m-d') }}
                                            </td>
                                            <td>
                                                {{ $customer->pataz }}
                                            </td>
                                            <td class="td-actions text-right">
                                                <form action="{{ route('customer.destroy', $customer) }}" method="post">
                                                    @csrf
                                                    @method('delete')

                                                    <a rel="tooltip" class="btn btn-success btn-link"
                                                       href="{{ route('customer.edit', $customer) }}" data-original-title=""
                                                       title="">
                                                        <i class="material-icons">edit</i>
                                                        <div class="ripple-container"></div>
                                                    </a>
                                                    <button type="button" class="btn btn-danger btn-link"
                                                            data-original-title="" title=""
                                                            onclick="confirm('{{ __("Tem certeza que deseja deletar este cliente?") }}') ? this.parentElement.submit() : ''">
                                                        <i class="material-icons">close</i>
                                                        <div class="ripple-container"></div>
                                                    </button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection