routes/web.php
<?php

Route::get('/', 'HomeController@index')->name('index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::resource('customer', 'CustomersController');
	Route::resource('vet', 'VetsController');
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
});

app/Vets.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Vets extends Model
{
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function petTypes()
    {
        return $this->hasMany(PetTypeVet::class, 'vet_id');
    }
}

app/Http/Controllers/VetsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\VetRequest;
use App\PetTypes;
use App\PetTypeVet;
use App\Role;
use App\User;
use App\Vets;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class VetsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Vets $model)
    {
        return view('vets.index', ['vets' => $model->paginate(15)]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('vets.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(VetRequest $request)
    {
        $user = new User();
        $user->name = $request->name;
        $user->email = $request->email;
        $user->password = Hash::make($request->password);
        $user->role_id = Role::VETERINARIO;
        $user->created_at = now();
        $user->save();

        $vet = new Vets();
        $vet->identity_number = $request->identity_number;
        $vet->cpf = $request->cpf;
        $vet->board_registration = $request->board_registration;
        $vet->user_id = $user->id;
        $vet->save();

        if ($request->pets_type_id) {
            foreach ($request->pets_type_id as $petTypeId) {
                $petType = new PetTypeVet();
                $petType->pet_type_id = $petTypeId;
                $petType->vet_id = $vet->id;
                $petType->save();
            }
        }

        return redirect()->route('vet.index')->withStatus(__('Veterinário criado com sucesso.'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Vets  $vets
     * @return \Illuminate\Http\Response
     */
    public function show(Vets $vets)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Vets  $vet
     * @return \Illuminate\Http\Response
     */
    public function edit(Vets $vet)
    {
        return view('vets.edit', compact('vet'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Vets  $vets
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Vets $vet)
    {
        $vet->user->name = $request->name;
        $vet->user->email = $request->email;
        $vet->user->save();
        $vet->identity_number = $request->identity_number;
        $vet->cpf = $request->cpf;
        $vet->board_registration = $request->board_registration;
        $vet->save();

        $vet->petTypes()->delete();
        if ($request->pets_type_id) {
            foreach ($request->pets_type_id as $petTypeId) {
                $petType = new PetTypeVet();
                $petType->pet_type_id = $petTypeId;
                $petType->vet_id = $vet->id;
                $petType->save();
            }
        }

        return redirect()->route('vet.index')->withStatus(__('Veterinário atualizado com sucesso.'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Vets  $vets
     * @return \Illuminate\Http\Response
     */
    public function destroy(Vets $vet)
    {
        $user = $vet->user;
        $vet->delete();
        $user->delete();

        return redirect()->route('vet.index')->withStatus(__('Veterinário removido com sucesso.'));
    }
}

resources/views/vets/create.blade.php
@extends('layouts.app', ['activePage' => 'vets', 'titlePage' => __('Criação de veterinário')])

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <form method="post" action="{{ route('vet.store') }}" autocomplete="off" class="form-horizontal">
                        @csrf
                        @method('post')

                        <div class="card ">
                            <div class="card-header card-header-primary">
                                <h4 class="card-title">{{ __('Novo veterinário') }}</h4>
                                <p class="card-category"></p>
                            </div>
                            <div class="card-body ">
                                <div class="row">
                                    <div class="col-md-12 text-right">
                                        <a href="{{ route('vet.index') }}"
                                           class="btn btn-sm btn-primary">{{ __('Voltar para lista') }}</a>
                                    </div>
                                </div>

                                <div class="row">
                                    <label class="col-sm-2 col-form-label">{{ __('Nome') }}</label>
                                    <div class="col-sm-7">
                                        <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                            <input class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}"
                                                   name="name" id="input-name" type="text"
                                                   placeholder="{{ __('Nome') }}" value="{{ old('name') }}"
                                                   required="true" aria-required="true"/>
                                            @if ($errors->has('name'))
                                                <span id="name-error" class="error text-danger"
                                                      for="input-name">{{ $errors->first('name') }}</span>
                                            @endif
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <label class="col-sm-2 col-form-label">{{ __('Email') }}</label>
                                    <div class="col-sm-7">
                                        <div class="form-group{{ $errors->has('email') ? ' has-danger' : '' }}">
                                            <input class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}"
                                                   name="email" id="input-email" type="email"
                                                   placeholder="{{ __('Email') }}" value="{{ old('email') }}" required/>
                                            @if ($errors->has('email'))
                                                <span id="email-error" class="error text-danger"
                                                      for="input-email">{{ $errors->first('email') }}</span>
                                            @endif
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <label class="col-sm-2 col-form-label">{{ __('CPF') }}</label>
                                    <div class="col-sm-7">
                                        <div class="form-group{{ $errors->has('cpf') ? ' has-danger' : '' }}">
                                            <input class="form-control{{ $errors->has('cpf') ? ' is-invalid' : '' }}"
                                                   name="cpf" id="input-cpf" type="text" min="11" max="11"
                                                   placeholder="{{ __('CPF') }}" value="{{ old('cpf') }}" required/>
                                            @if ($errors->has('cpf'))
                                                <span id="cpf-error" class="error text-danger"
                                                      for="input-cpf">{{ $errors->first('cpf') }}</span>
                                            @endif
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <label class="col-sm-2 col-form-label">{{ __('Número de identidade') }}</label>
                                    <div class="col-sm-7">
                                        <div class="form-group{{ $errors->has('identity_number') ? ' has-danger' : '' }}">
                                            <input class="form-control{{ $errors->has('identity_number') ? ' is-invalid' : '' }}"
                                                   name="identity_number" id="input-identity_number" type="text"
                                                   placeholder="{{ __('Número de identidade') }}" value="{{ old('identity_number') }}" required/>
                                            @if ($errors->has('identity_number'))
                                                <span id="identity_number-error" class="error text-danger"
                                                      for="input-identity_number">{{ $errors->first('identity_number') }}</span>
                                            @endif
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <label class="col-sm-2 col-form-label">{{ __('Registro no CFMV') }}</label>
                                    <div class="col-sm-7">
                                        <div class="form-group{{ $errors->has('board_registration') ? ' has-danger' : '' }}">
                                            <input class="form-control{{ $errors->has('board_registration') ? ' is-invalid' : '' }}"
                                                   name="board_registration" id="input-board_registration" type="text"
                                                   placeholder="{{ __('Registro no CFMV') }}" value="{{ old('board_registration') }}" required/>
                                            @if ($errors->has('board_registration'))
                                                <span id="board_registration-error" class="error text-danger"
                                                      for="input-board_registration">{{ $errors->first('board_registration') }}</span>
                                            @endif
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <label class="col-sm-2 col-form-label"
                                           for="input-pets-type">{{ __('Tipos de Pet') }}</label>
                                    <div class="col-sm-7">
                                        <div class="form-group">
                                            <select class="form-control chosen-select" id="input-pets-type-id"
                                                    name="pets_type_id[]" required
                                                    data-placeholder="Escolha os tipos de Pet" multiple>
                                                <option id=""></option>
                                                @foreach (\App\PetTypes::all() as $petType)
                                                    <option value="{{ $petType->id }}">{{ $petType->label }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <label class="col-sm-2 col-form-label"
                                           for="input-password">{{ __(' Senha') }}</label>
                                    <div class="col-sm-7">
                                        <div class="form-group{{ $errors->has('password') ? ' has-danger' : '' }}">
                                            <input
                                                class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}"
                                                input type="password" name="password" id="input-password"
                                                placeholder="{{ __('Senha') }}" value="" required/>
                                            @if ($errors->has('password'))
                                                <span id="name-error" class="error text-danger"
                                                      for="input-name">{{ $errors->first('password') }}</span>
                                            @endif
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <label class="col-sm-2 col-form-label"
                                           for="input-password-confirmation">{{ __('Confirmação de senha') }}</label>
                                    <div class="col-sm-7">
                                        <div class="form-group">
                                            <input class="form-control" name="password_confirmation"
                                                   id="input-password-confirmation" type="password"
                                                   placeholder="{{ __('Confirmação de senha') }}" value="" required/>
                                        </div>
                                    </div>
                                </div>

                            </div>
                            <div class="card-footer ml-auto mr-auto">
                                <button type="submit" class="btn btn-primary">{{ __('Criar veterinário') }}</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('css')
    <link href="{{ asset('js') }}/chosenjs/chosen.min.css" rel="stylesheet" />
@endpush

@push('js')
    <script src="{{ asset('js') }}/chosenjs/chosen.jquery.min.js"></script>
    <script type="application/javascript">
        $( document ).ready(function() {
            $(".chosen-select").chosen();
        });
    </script>
@endpush

resources/views/vets/edit.blade.php
@extends('layouts.app', ['activePage' => 'vets', 'titlePage' => __('Edição de veterinário')])

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <form method="post" action="{{ route('vet.update', $vet) }}" autocomplete="off" class="form-horizontal">
                        @csrf
                        @method('put')

                        <div class="card ">
                            <div class="card-header card-header-primary">
                                <h4 class="card-title">{{ __('Editar veterinário') }}</h4>
                                <p class="card-category"></p>
                            </div>
                            <div class="card-body ">
                                <div class="row">
                                    <div class="col-md-12 text-right">
                                        <a href="{{ route('vet.index') }}"
                                           class="btn btn-sm btn-primary">{{ __('Voltar para lista') }}</a>
                                    </div>
                                </div>

                                <div class="row">
                                    <label class="col-sm-2 col-form-label">{{ __('Nome') }}</label>
                                    <div class="col-sm-7">
                                        <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                            <input class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}"
                                                   name="name" id="input-name" type="text"
                                                   placeholder="{{ __('Nome') }}" value="{{ old('name', $vet->user->name) }}"
                                                   required="true" aria-required="true"/>
                                            @if ($errors->has('name'))
                                                <span id="name-error" class="error text-danger"
                                                      for="input-name">{{ $errors->first('name') }}</span>
                                            @endif
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <label class="col-sm-2 col-form-label">{{ __('Email') }}</label>
                                    <div class="col-sm-7">
                                        <div class="form-group{{ $errors->has('email') ? ' has-danger' : '' }}">
                                            <input class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}"
                                                   name="email" id="input-email" type="email"
                                                   placeholder="{{ __('Email') }}" value="{{ old('email', $vet->user->email) }}" required/>
                                            @if ($errors->has('email'))
                                                <span id="email-error" class="error text-danger"
                                                      for="input-email">{{ $errors->first('email') }}</span>
                                            @endif
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <label class="col-sm-2 col-form-label">{{ __('CPF') }}</label>
                                    <div class="col-sm-7">
                                        <div class="form-group{{ $errors->has('cpf') ? ' has-danger' : '' }}">
                                            <input class="form-control{{ $errors->has('cpf') ? ' is-invalid' : '' }}"
                                                   name="cpf" id="input-cpf" type="text" min="11" max="11"
                                                   placeholder="{{ __('CPF') }}" value="{{ old('cpf', $vet->cpf) }}" required/>
                                            @if ($errors->has('cpf'))
                                                <span id="cpf-error" class="error text-danger"
                                                      for="input-cpf">{{ $errors->first('cpf') }}</span>
                                            @endif
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <label class="col-sm-2 col-form-label">{{ __('Número de identidade') }}</label>
                                    <div class="col-sm-7">
                                        <div class="form-group{{ $errors->has('identity_number') ? ' has-danger' : '' }}">
                                            <input class="form-control{{ $errors->has('identity_number') ? ' is-invalid' : '' }}"
                                                   name="identity_number" id="input-identity_number" type="text"
                                                   placeholder="{{ __('Número de identidade') }}" value="{{ old('identity_number', $vet->identity_number) }}" required/>
                                            @if ($errors->has('identity_number'))
                                                <span id="identity_number-error" class="error text-danger"
                                                      for="input-identity_number">{{ $errors->first('identity_number') }}</span>
                                            @endif
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <label class="col-sm-2 col-form-label">{{ __('Registro no CFMV') }}</label>
                                    <div class="col-sm-7">
                                        <div class="form-group{{ $errors->has('board_registration') ? ' has-danger' : '' }}">
                                            <input class="form-control{{ $errors->has('board_registration') ? ' is-invalid' : '' }}"
                                                   name="board_registration" id="input-board_registration" type="text"
                                                   placeholder="{{ __('Registro no CFMV') }}" value="{{ old('board_registration', $vet->board_registration) }}" required/>
                                            @if ($errors->has('board_registration'))
                                                <span id="board_registration-error" class="error text-danger"
                                                      for="input-board_registration">{{ $errors->first('board_registration') }}</span>
                                            @endif
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <label class="col-sm-2 col-form-label"
                                           for="input-pets-type">{{ __('Tipos de Pet') }}</label>
                                    <div class="col-sm-7">
                                        <div class="form-group">
                                            <select class="form-control chosen-select" id="input-pets-type-id"
                                                    name="pets_type_id[]" required
                                                    data-placeholder="Escolha os tipos de Pet" multiple>
                                                <option id=""></option>
                                                @foreach (\App\PetTypes::all() as $petType)
                                                    <option value="{{ $petType->id }}"
                                                    @if($vet->petTypes->where('pet_type_id', $petType->id)->isNotEmpty()) selected @endif
                                                    >{{ $petType->label }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                </div>

                            <div class="card-footer ml-auto mr-auto">
                                <button type="submit" class="btn btn-primary">{{ __('Salvar') }}</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('css')
    <link href="{{ asset('js') }}/chosenjs/chosen.min.css" rel="stylesheet" />
@endpush

@push('js')
    <script src="{{ asset('js') }}/chosenjs/chosen.jquery.min.js"></script>
    <script type="application/javascript">
        $( document ).ready(function() {
            $(".chosen-select").chosen();
        });
    </script>
@endpush

resources/views/vets/index.blade.php
@extends('layouts.app', ['activePage' => 'vets', 'titlePage' => __('Veterinários')])

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-primary">
                            <h4 class="card-title ">{{ __('Veterinários') }}</h4>
                            <p class="card-category"> {{ __('Listagem de veterinários') }}</p>
                        </div>
                        <div class="card-body">
                            @if (session('status'))
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class="alert alert-success">
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                <i class="material-icons">close</i>
                                            </button>
                                            <span>{{ session('status') }}</span>
                                        </div>
                                    </div>
                                </div>
                            @endif
                            <div class="row">
                                <div class="col-12 text-right">
                                    <a href="{{ route('vet.create') }}"
                                       class="btn btn-sm btn-primary">{{ __('Novo veterinário') }}</a>
                                </div>
                            </div>
                            <div class="table-responsive">
                                <table class="table">
                                    <thead class=" text-primary">
                                    <th>
                                        {{ __('Nome') }}
                                    </th>
                                    <th>
                                        {{ __('Email') }}
                                    </th>
                                    <th>
                                        {{ __('Data de criação') }}
                                    </th>
                                    <th>
                                        {{ __('CPF') }}
                                    </th>
                                    <th>
                                        {{ __('Registro CFMV') }}
                                    </th>
                                    <th>
                                        {{ __('Pets') }}
                                    </th>
                                    <th class="text-right">
                                        {{ __('Ações') }}
                                    </th>
                                    </thead>
                                    <tbody>
                                    @foreach($vets as $vet)
                                        <tr>
                                            <td>
                                                {{ $vet->user->name }}
                                            </td>
                                            <td>
                                                {{ $vet->user->email }}
                                            </td>
                                            <td>
                                                {{ $vet->user->created_at->format('Y-m-d') }}
                                            </td>
                                            <td>
                                                {{ $vet->cpf }}
                                            </td>
                                            <td>
                                                {{ $vet->board_registration }}
                                            </td>
                                            <td>
                                                @foreach ($vet->petTypes as $petType)
                                                    {{ $petType->petType->label }}
                                                @endforeach
                                            </td>
                                            <td class="td-actions text-right">
                                                <form action="{{ route('vet.destroy', $vet) }}" method="post">
                                                    @csrf
                                                    @method('delete')

                                                    <a rel="tooltip" class="btn btn-success btn-link"
                                                       href="{{ route('vet.edit', $vet) }}" data-original-title=""
                                                       title="">
                                                        <i class="material-icons">edit</i>
                                                        <div class="ripple-container"></div>
                                                    </a>
                                                    <button type="button" class="btn btn-danger btn-link"
                                                            data-original-title="" title=""
                                                            onclick="confirm('{{ __("Tem certeza que deseja deletar este veterinário?") }}') ? this.parentElement.submit() : ''">
                                                        <i class="material-icons">close</i>
                                                        <div class="ripple-container"></div>
                                                    </button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection